### PR TITLE
cam rotation support

### PR DESCRIPTION
**Pull request by lunacynne**
implementation of world space camera rotation via a `rotation` property

https://github.com/FunkinCrew/flixel/assets/58795684/e2109405-e29c-4a28-b8c8-9112c141b3e7

### CODE REVIEW

**Comment by Raltyro** [comment]
Why hasn't this been in base flixel yet...

**Comment by ACrazyTown** [comment]
Why not PR this to the main flixel repository?

**Comment by lunacynne** [comment]
> Why not PR this to the main flixel repository?

i will! i just wanted it here first so it can get implemented ingame faster

**Comment by lunacynne** [comment]
> > Why not PR this to the main flixel repository?
> 
> i will! i just wanted it here first so it can get implemented ingame faster

turns out they already have a better implementation planned for world-space rotation (though itll take time, on the 7.0.0 milestone)

should i close this pr or keep open? myself as well as some people i know have immediate use cases for this, so while a better implementation would be nice, itll probably be a long time for it to make it to flixel and then to this repo and then finally into the game

**Comment by AbnormalPoof** [comment]
I'd say keep it open if it's going to take a while (like a very long time) for it to be in base Flixel. FunkinCrew's flixel fork seems to be exclusively used on FNF, so having cam rotation specifically for FNF would be nice. The official implementation for camera rotation can also simply act as the replacement later down the line when it makes it into base Flixel.

**Comment by lunacynne** [comment]
closed... this is getting added as a feature? or was it just stale for too long?

**Comment by ninjamuffin99** [comment]
not added as a feature, recommend you making PR to upstream flixel instead of FunkinCrew

**Comment by Raltyro** [comment]
ants are eating the skin
the pr in flixel with the same goal is inactive too

**Comment by lunacynne** [comment]
> ants are eating the skin
> the pr in flixel with the same goal is inactive too

yea im guessing its gonna be a good long while until that makes it into fnf...
hoping to find some script based solution for my use case in the meantime but im not even sure if thats possible
i just wanna rotate the damn camera space :WAAAAAAAAAHHHH:

**Pull request closed without merging**
